#lang reader "RangReader_test.rkt"
STR
AOA OIA AOA OIA OIA CAZ IIA OIA OIB STP
NOP PUP RLF STP
NEW
NOP NOP NOP STP
NOP RRT OIA PUP STP
NEW
NOP NOP NOP NOP STP
RDW OIA OIA RLF STP
RRT OIA IIA OIA STP
END