#lang reader "RangReader.rkt"
NEW
STO STP
RRT AOA AOA AOA AOA AOA AOA AOA AOA AOA AOA RDW STP
PUP NOP NOP NOP NOP NOP NOP NOP NOP CPA PEB RLF STP
NEW
STO STP
PDW STP
PUP STP
STR
NEA REA PEB PEB AOB RDW STP
PDW NOP NEB NEB NOP RLF STP
RRT OIA STP
END



