#lang reader "RangReader.rkt"
NEW
STO STP
STR
PUP NOP RRT NOP NOP NOP RRT CAZ PUP OIA SOA RDW STP 
RRT NOP RUP NOP NOP NOP RUP NOP NOP NOP NOP RLF STP
NEW
RRT AOA AOA AOA AOA AOA NEB RDW RDW STP
PDW AOA AOA AOA AOA AOA NOP RLF RRT OIB STO STP
END



