#lang reader "RangReader.rkt"

NEW
IIA NEB IIB ADA AOA OIA STP


NEW
RDW NOP RLF NOP RLF NOP NOP NOP NOP STP
NOP NOP RUP NOP SOA PEA RLF STP
RRT NOP CAZ PUP NEA ADA RUP RUP NOP STP

NEW
NOP NOP NOP NOP RRT OIB STP
NOP STP
STO OIA NEA RLF OIA STP
NEW
NOP NOP NOP NOP CBZ STP
NEW
NOP NOP NOP NOP RRT OIA STP
NEW
NOP NOP NOP NOP CAZ STP

STR 
NEA IIA NOP IIB PDW STP
END